# Playbooks
- name: Include Homelab container
  ansible.builtin.import_playbook: playbooks/proxmox/homelab.yml

- name: Include Tailscale container
  ansible.builtin.import_playbook: playbooks/proxmox/tailscale.yml

- name: Include vars
  ansible.builtin.import_playbook: playbooks/include_vars.yml

- name: Run pre-check
  ansible.builtin.import_playbook: playbooks/pre_check.yml

# Roles
## Proxmox
- name: Run Common Roles
  hosts: proxmox
  gather_facts: false
  roles:
    - role: common
      become: true
      vars:
        ssh_config: "{{ ssh }}"
        ssh_user: "{{ ssh_user }}"
        ssh_password: "{{ ssh_password }}"
        ssh_public_key: "{{ ssh_public_key }}"

        ufw_config: "{{ ufw }}"

- name: Run pre-check
  ansible.builtin.import_playbook: playbooks/pre_check.yml

## Homelab
- name: Run Homelab Roles
  hosts: homelab
  gather_facts: false
  roles:
    - role: common
      become: true
      vars:
        docker_config: "{{ docker }}"

        caddy_config: "{{ caddy }}"
        caddy_domain: "{{ caddy_domain }}"
        caddy_cloudflare_email: "{{ caddy_cloudflare_email }}"
        caddy_cloudflare_token: "{{ caddy_cloudflare_token }}"
    
    - role: docker
      become: true
      vars:
        docker_user_uid: "{{ docker_user_uid }}"
        docker_user_gid: "{{ docker_user_gid }}"
        docker_tz: "{{ docker_tz }}"

        filebrowser: "{{ filebrowser }}"
        transmission: "{{ transmission }}"
        flame: "{{ flame }}"
        
        pihole: "{{ pihole }}"
        pihole_password: "{{ pihole_password }}"

        jellyfin: "{{ jellyfin }}"
        watchtower: "{{ watchtower }}"

## Tailscale
- name: Run Tailscale Role
  hosts: tailscale
  gather_facts: true
  become: true
  roles:
    - role: tailscale
      become: true
      vars:
        auth_key: "{{ tailscale_auth_key }}"