---
#Basic
#- import_playbook: ../tasks/basic/ssh/tasks/install.yml
#- import_playbook: ../tasks/basic/tailscale/tasks/install.yml
#- import_playbook: ../tasks/basic/caddy/tasks/install.yml

#Docker
#- import_playbook: ../tasks/docker/tasks/install.yml
- import_playbook: ../tasks/docker/tasks/duplicati.yml

- hosts: all
  tasks:
    - ansible.builtin.pause:
        prompt: "Press Enter when finished to continue ..."

- import_playbook: ../tasks/docker/tasks/mariadb.yml
- import_playbook: ../tasks/docker/tasks/portainer.yml
- import_playbook: ../tasks/docker/tasks/homepage.yml
- import_playbook: ../tasks/docker/tasks/vaultwarden.yml
- import_playbook: ../tasks/docker/tasks/pihole.yml
- import_playbook: ../tasks/docker/tasks/webdav.yml
- import_playbook: ../tasks/docker/tasks/duplicati-dashboard.yml

#Commands
# mount /dev/sdb1 /opt/backups/ - To mount the disk