ssh_config: false
ufw_config: false
docker_config: false
caddy_config: false

caddy_url: "https://caddyserver.com/api/download?os=linux&arch=arm64&p=github.com%2Fcaddy-dns%2Fcloudflare&idempotency=39231016207865"
caddy_domain: "example.com"
caddy_cloudflare_email: "example@example.com"
caddy_cloudflare_token: "123456789"