container_id: 200
container_name: "ansible-deployment"
container_description: "Container created successfully with Ansible"
container_password: "123456"

container_onboot: true
container_cpus: "1"
container_cores: "1"
container_memory: "1024"
container_network: '{"net0":"name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr0"}'