- name: Create Proxmox LXC Container
  community.general.proxmox:
    node: "{{ node }}"
    vmid: "{{ container_id }}"
    hostname: "{{ container_name }}"
    description: "{{ container_description }}"
    password: "{{ container_password }}"

    ostemplate: "{{ container_template }}"
    onboot: "{{ container_onboot }}"
    state: "present"

    cpus: "{{ container_cpus }}"
    cores: "{{ container_cores }}"
    memory: "{{ container_memory }}"
    netif: '{{ container_network }}'
        
    validate_certs: false
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"

    timeout: 600
  notify: Start Proxmox LXC Container