---
- hosts: docker
  become: yes
  
  tasks:

    - include_vars: "{{ vars_folder }}"

    - include_vars: ../vars/rpi(bullseye).json
      when: ansible_architecture == "aarch64" and ansible_distribution == "Debian"

    - include_vars: ../vars/x86.json
      when: ansible_architecture == "x86_64" and ansible_distribution == "Ubuntu"

    - name: Download
      ansible.builtin.get_url:
        url: "{{ url }}"
        dest: /tmp/seq.tar.gz

    - name: Creates directory
      file:
        path: /opt/cli/seq
        state: directory

    - name: Extract
      ansible.builtin.unarchive:
        src: /tmp/seq.tar.gz
        dest: /opt/cli/seq
        extra_opts: [--strip-components=1]
        remote_src: yes

    - name: Change the default url
      ansible.builtin.shell: /opt/cli/seq/seqcli config -k connection.serverUrl -v https://seq.{{ domain }}

    - name: Create the ApiKey
      ansible.builtin.shell: /opt/cli/seq/seqcli apikey create -t CLI --permissions="Read,Write,Ingest" --connect-username {{ seq_user }} --connect-password '{{ seq_password }}'
      register: api

    - name: Add the ApiKey
      ansible.builtin.shell: /opt/cli/seq/seqcli config -k connection.apiKey -v {{ api.stdout }}
