---
- hosts: docker
  become: true

  tasks:
    - include_vars: ../../../../../vars/main.json

    - name: Install all dependencies
      ansible.builtin.package:
        name:
          - inotify-tools
          - jq
        state: latest
        update_cache: yes

    # UFW

    - name: Create the directory
      file:
          path: /opt/scripts
          state: directory
          owner: root
          group: root

    - name: Create systemd service
      template:
          src: ../templates/ufwscript.service.j2
          dest: /lib/systemd/system/ufwscript.service
          owner: root
          group: root

    - name: Create the script file
      ansible.builtin.template:
        src: ../templates/ufw.sh.j2
        dest: /opt/scripts/ufw.sh
        owner: root
        group: root
        mode: '0774'

    - name: Restart the service
      ansible.builtin.service:
        name: ufwscript
        state: restarted
        enabled: yes

    # SSH

    - name: Add line to .profile
      ansible.builtin.blockinfile:
        path: /home/{{ user_systemd }}/.profile
        block: |
          /opt/scripts/ssh.sh

    - name: Create script
      copy:
        dest: "/opt/scripts/ssh.sh"
        content: |
          #!/bin/bash
          IP=$(echo $SSH_CLIENT | awk '{ print $1}')
          /opt/cli/seq/seqcli log -l Warning -m "Someone is in the server." -p Server=$(hostname) -p ForeignIP=$(echo $IP) -p Service=SSH
    
    - name: Adding "+x"
      file:
        dest: /opt/scripts/ssh.sh
        mode: a+x

    # Caddy

    - name: Create the directory
      file:
          path: /var/log/caddy
          state: directory
          owner: "{{ user_systemd }}"
          group: "{{ group_systemd }}"

    - name: Create systemd service
      template:
          src: ../templates/caddyscript.service.j2
          dest: /lib/systemd/system/caddyscript.service
          owner: root
          group: root

    - name: Create the script file
      ansible.builtin.template:
        src: ../templates/caddy.sh.j2
        dest: /opt/scripts/caddy.sh
        owner: root
        group: root
        mode: '0774'

    - name: Restart the service
      ansible.builtin.service:
        name: caddyscript
        state: restarted
        enabled: yes
