---
- hosts: docker
  become: yes
  
  tasks:
    - include_vars: ../../../../../vars/main.json

    - name: Create user and database
      community.docker.docker_container_exec:
        container: mariadb
        command: mysql -u {{ mariadb_user }} --password={{ mariadb_user_password }} --execute="CREATE USER IF NOT EXISTS '{{ nextcloud_user }}'@'%' IDENTIFIED BY '{{ nextcloud_password }}';GRANT USAGE ON *.* TO '{{ nextcloud_user }}'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;CREATE DATABASE IF NOT EXISTS {{ nextcloud_user }};GRANT ALL PRIVILEGES ON {{ nextcloud_user }}.* TO '{{ nextcloud_user }}'@'%';"

    - name: Deploy Nextcloud
      community.docker.docker_container:
        name: nextcloud
        recreate: yes
        image: nextcloud:latest
        ports:
          - "127.0.0.1:9011:80"
        volumes:
          - "/opt/docker/nextcloud/data:/var/www/html"
        links:
          - "mariadb:db"
        env:
          MYSQL_HOST: "db"
          MYSQL_DATABASE: "{{ nextcloud_user }}"
          MYSQL_USER: "{{ nextcloud_user }}"
          MYSQL_PASSWORD: "{{ nextcloud_password }}"
        restart_policy: always
        labels:
          homepage.group: Services
          homepage.name: Nextcloud
          homepage.href: https://nextcloud.{{ domain }}
          homepage.description: Cloud storage