---
- hosts: docker
  become: yes

  tasks:
    - name: Deploy Homepage
      community.docker.docker_container:
        name: homepage
        recreate: yes
        image: ghcr.io/benphelps/homepage:latest
        ports:
          - "127.0.0.1:9001:3000"
        volumes:
          - /opt/docker/homepage/config:/app/config
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: always