---
- hosts: docker
  become: yes

  tasks:
    - include_vars: ../vars/main.json
    
    - name: Deploy Portainer
      community.docker.docker_container:
        name: portainer
        recreate: yes
        image: portainer/portainer-ce
        ports:
          - "9000:9000"
          - "8000:8000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /opt/docker/portainer:/data
        restart_policy: always
        labels:
          homepage.group: Management
          homepage.name: Portainer
          homepage.href: https://portainer{{ homepage_domain }}
          homepage.description: Docker interface
