---
- hosts: docker
  become: yes
  
  tasks:
    - include_vars: ../../../../../vars/main.json

    - name: Deploy Pi-Hole
      community.docker.docker_container:
          name: pihole
          recreate: yes
          image: pihole/pihole:latest
          ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "127.0.0.1:9004:80/tcp"
          volumes:
            - /opt/docker/pihole/config:/etc/pihole
            - /opt/docker/pihole/dnsmasq:/etc/dnsmasq.d
          env:
            TZ: "Europe/Madrid"
            WEBPASSWORD: "{{ pihole_password }}"
          restart_policy: always
          labels:
            homepage.group: Management
            homepage.name: Pi-Hole
            homepage.href: https://pihole.{{ domain }}
            homepage.description: DNS ad-blocking