---
- hosts: docker
  become: yes
  
  tasks:
    - include_vars: "{{ vars_folder }}"

    - name: Deploy PyLoad
      community.docker.docker_container:
        name: pyload
        recreate: yes
        image: lscr.io/linuxserver/pyload-ng:latest
        ports:
          - "127.0.0.1:9013:8000"
        env:
          TZ: "Etc/UTC"
        volumes:
          - /opt/docker/pyload/config:/config
          - /opt/docker/pyload/data:/downloads
        restart_policy: always
        labels:
          homepage.group: Services
          homepage.name: PyLoad
          homepage.href: https://download.{{ domain }}
          homepage.description: Download manager
          com.centurylinklabs.watchtower.enable: "true"