---
- hosts: docker
  become: yes
  
  tasks:
    - include_vars: ../../../../../vars/main.json

    - name: Encrypt the password
      ansible.builtin.shell:
        cmd: echo '{{ seq_password }}' | sudo docker run --rm -i datalust/seq config hash
      register: password
    
    - name: Deploy Seq
      community.docker.docker_container:
        name: seq
        recreate: yes
        image: datalust/seq
        ports:
          - "127.0.0.1:9012:80"
        volumes:
          - "/opt/docker/seq:/data"
        env:
          ACCEPT_EULA: "Y"
          SEQ_FIRSTRUN_ADMINUSERNAME: "{{ seq_user }}"
          SEQ_FIRSTRUN_ADMINPASSWORDHASH: "{{ password.stdout }}"
        restart_policy: always
        labels:
          homepage.group: Management
          homepage.name: Seq
          homepage.href: https://seq.{{ domain }}
          homepage.description: Applications logs