---
- hosts: tailscale
  become: yes
  
  tasks:
    - include_vars: "{{ vars_folder }}"

    - include_vars: ../vars/rpi(bullseye).json
      when: ansible_architecture == "aarch64" and ansible_distribution == "Debian"

    - include_vars: ../vars/x86(focal).json
      when: ansible_architecture == "x86_64" and ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "20"

    - include_vars: ../vars/x86(jammy).json
      when: ansible_architecture == "x86_64" and ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "22"

    - name: Get the GPG key
      ansible.builtin.get_url:
        url: "{{ tailscale_gpg }}"
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        mode: '0644'
        force: true

    - name: Get the list
      ansible.builtin.get_url:
        url: "{{ tailscale_list }}"
        dest: /etc/apt/sources.list.d/tailscale.list
        mode: '0644'
        force: true

    - name: Install tailscale
      ansible.builtin.package:
        name:
          - tailscale
        state: latest
        update_cache: yes

    - name: Append to `/etc/sysctl.conf`
      ansible.builtin.shell: |
        modprobe xt_mark
        echo 'net.ipv4.ip_forward = 1' | tee -a /etc/sysctl.conf
        echo 'net.ipv6.conf.all.forwarding = 1' | tee -a /etc/sysctl.conf
        echo 'net.ipv6.conf.all.disable_policy = 1' | tee -a /etc/sysctl.conf
        iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
        ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

    - name: Declare exit node
      ansible.builtin.shell: /usr/bin/tailscale up --authkey={{ tailscale_key }} --advertise-routes=10.0.0.0/24 --advertise-exit-node