---
- hosts: docker
  become: yes
  
  tasks:
    - include_vars: "{{ vars_folder }}"

    - name: Deploy PhpMyAdmin
      community.docker.docker_container:
        name: phpmyadmin
        recreate: yes
        image: phpmyadmin:latest
        ports:
          - "127.0.0.1:9003:80"
        links:
          - mariadb:mariadb
          - mysql:mysql
        env:
          PMA_ARBITRARY: "1"
        restart_policy: always
        labels:
          homepage.group: Management
          homepage.name: PHP My Admin
          homepage.href: https://phpmyadmin.{{ domain }}
          homepage.description: Web interface for Maria DB and MySQL