---
- hosts: docker
  become: yes
  
  tasks:
    - include_vars: "{{ vars_folder }}"
    
    - name: Deploy Postgres
      community.docker.docker_container:
        name: postgres
        recreate: yes
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: "{{ postgres_user }}"
          POSTGRES_PASSWORD: "{{ postgres_user_password }}"
          PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
          - /opt/docker/postgres/data:/var/lib/postgresql/data
        restart_policy: always

    - name: Deploy PGadmin
      community.docker.docker_container:
        name: pgadmin
        recreate: yes
        image: dpage/pgadmin4:latest
        ports:
          - "127.0.0.1:9009:80"
        links:
          postgres:db
        env:
          PGADMIN_DEFAULT_EMAIL: "{{ pgadmin_email }}"
          PGADMIN_DEFAULT_PASSWORD: "{{ pgadmin_password }}"
          PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
          PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "10"
        volumes:
          - /opt/docker/postgres/data:/var/lib/postgresql/data
        restart_policy: always
        labels:
          homepage.group: Management
          homepage.name: PGadmin
          homepage.href: https://pgadmin.{{ domain }}
          homepage.description: Postgres administration
          com.centurylinklabs.watchtower.enable: "true"