---
- hosts: tailscale
  become: yes
  
  tasks:
    - name: Remove the GPG key
      file:
        path: /usr/share/keyrings/tailscale-archive-keyring.gpg
        state: absent

    - name: Remove the list
      file:
        path: /etc/apt/sources.list.d/tailscale.list
        state: absent

    - name: Uninstall tailscale
      ansible.builtin.package:
        name:
          - tailscale
        state: absent