---
- hosts: docker
  become: yes

  tasks:

    - name: Stop the service
      ansible.builtin.service:
        name: caddy
        state: stopped
        enabled: no

    - name: Remove the binary
      file:
        path: /usr/local/bin/caddy
        state: absent

    - name: Remove the etc folder
      file:
          path: /etc/caddy
          state: absent

    - name: Remove the ssl folder
      file:
          path: /etc/ssl/caddy
          state: absent

    - name: Remove the systemd file
      file:
          path: /lib/systemd/system/caddy.service
          state: absent

    