---
- name: Creates Config directory
  ansible.builtin.file:
    path: /opt/docker/homarr/config
    state: directory

- name: Creates Icons directory
  ansible.builtin.file:
    path: /opt/docker/homarr/icons
    state: directory

- name: Creates Data directory
  ansible.builtin.file:
    path: /opt/docker/homarr/data
    state: directory

- name: Deploy Homarr
  community.docker.docker_container:
    name: homarr
    recreate: yes
    image: ghcr.io/ajnart/homarr:latest
    ports:
      - "127.0.0.1:9999:7575"
    volumes:
      - /opt/docker/homarr/config:/app/data/configs
      - /opt/docker/homarr/icons:/app/public/icons
      - /opt/docker/homarr/data:/data
    restart_policy: always