- name: Creates directory
  ansible.builtin.file:
    path: /opt/docker
    state: directory

- name: Deploy Filebrowser
  ansible.builtin.include_tasks: filebrowser.yml
  when: filebrowser | default(False)

- name: Deploy Transmission
  ansible.builtin.include_tasks: transmission.yml
  when: transmission | default(False)

- name: Deploy Flame
  ansible.builtin.include_tasks: flame.yml
  when: flame | default(False)

- name: Deploy Pi-Hole
  ansible.builtin.include_tasks: pihole.yml
  when: pihole | default(False)