- name: Creates directory
  ansible.builtin.file:
    path: /opt/docker
    state: directory

- name: Deploy Filebrowser
  ansible.builtin.include_tasks: filebrowser.yml
  when: filebrowser | default(False)

- name: Deploy Transmission
  ansible.builtin.include_tasks: transmission.yml
  when: transmission | default(False)

- name: Deploy Flame
  ansible.builtin.include_tasks: flame.yml
  when: flame | default(False)

- name: Deploy Pi-Hole
  ansible.builtin.include_tasks: pihole.yml
  when: pihole | default(False)

- name: Deploy Jellyfin
  ansible.builtin.include_tasks: jellyfin.yml
  when: jellyfin | default(False)

- name: Deploy Watchtower
  ansible.builtin.include_tasks: watchtower.yml
  when: watchtower | default(False)

- name: Deploy Watcharr
  ansible.builtin.include_tasks: watcharr.yml
  when: watcharr | default(False)