---
- hosts: docker
  become: yes

  tasks:
    - include_vars: "{{ vars_folder }}"
        
    - name: Deploy Duplicati
      community.docker.docker_container:
        name: duplicati
        recreate: yes
        image: duplicati/duplicati:latest
        ports:
          - "127.0.0.1:9002:8200"
        volumes:
          - /opt/docker/duplicati/config:/config
          - /opt/backups:/backups
          - /opt/docker:/source
          - /opt/docker/duplicati/data:/data
        restart_policy: always
        labels:
          homepage.group: Management
          homepage.name: Duplicati
          homepage.href: https://duplicati.{{ domain }}
          homepage.description: Backup software

    - ansible.builtin.pause:
        prompt: "Press Enter when finished to continue ..."
