---
- hosts: docker
  become: yes

  tasks:
    - name: Install Docker and Docker-Compose
      ansible.builtin.package:
        name:
          - docker.io
          - docker-compose
        state: latest

    - name: Create the directory
      ansible.builtin.file:
        path: /opt/docker
        state: directory
        mode: "0755"