---
- hosts: docker
  become: yes

  tasks:
    - include_vars: ../../vars/vars.json
    
    - name: Deploy Duplicati
      community.docker.docker_container:
        name: duplicati
        recreate: yes
        image: duplicati/duplicati:latest
        ports:
          - "9002:8200"
        volumes:
          - /opt/docker/duplicati/config:/config
          - /opt/backups:/backups
          - /opt/docker:/source
          - /opt/docker/duplicati/data:/data
        restart_policy: always
        labels:
          homepage.group: Management
          homepage.name: Duplicati
          homepage.href: http://{{ homepage_domain }}:9002
          homepage.description: Backup software
