name: Deploy with Semaphore
description: Deploy changes to a server

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:
    

jobs:
  deploy:
    name: Deploy the changes to the server
    runs-on: ubuntu-latest

    steps:
    - name: Login to Semaphore
      run: |
        curl -c /tmp/semaphore-cookie -XPOST -H 'Content-Type: application/json' -H 'Accept: application/json' -d '{"auth": "${{ secrets.SEMAPHORE_USER }}", "password": "${{ secrets.SEMAPHORE_PASS }}"}' "https://${{ secrets.SEMAPHORE_URL }}/api/auth/login"

    - name: Get Semaphore API key
      run: |
        curl -b /tmp/semaphore-cookie -XPOST -H 'Content-Type: application/json' -H "Connection: close" -H 'Accept: application/json' "https://${{ secrets.SEMAPHORE_URL }}/api/user/tokens" > test.txt

    - name: Extract Semaphore API key
      run: |
        cat test.txt | jq -r '.id' > hola.txt

    - name: Run task on Semaphore
      run: |
        curl -XPOST -H 'Content-Type: application/json' -H 'Accept: application/json' -H "Authorization: Bearer $(cat hola.txt)" -d '{"template_id": 1}' "https://${{ secrets.SEMAPHORE_URL }}/api/project/1/tasks"

    - name: Expire Semaphore API key
      run: |
        curl -X 'DELETE' -H 'accept: application/json' "https://${{ secrets.SEMAPHORE_URL }}/api/user/tokens/$(cat hola.txt)"

    - name: Logout of Semaphore
      run: |
        curl -X 'POST' "https://${{ secrets.SEMAPHORE_URL }}/api/auth/logout" -H 'accept: application/json' -d ''
    